name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install Xvfb (headless display)
      - name: Install Xvfb
        run: sudo apt-get install xvfb

      # Step 4: Start Xvfb (background process)
      - name: Start Xvfb
        run: Xvfb :99 &

      # Step 5: Set DISPLAY environment variable for Tkinter to work
      - name: Set DISPLAY environment variable
        run: export DISPLAY=:99

      # Step 6: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # Step 7: Run tests with Xvfb enabled
      - name: Run pytest
        run: |
          pytest tests/ --maxfail=5 --disable-warnings -v
