name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # Step 4: Show directory structure (for debugging)
      - name: Show directory structure
        run: |
          echo "Showing the directory structure"
          ls -R

      # Step 5: Show PYTHONPATH and sys.path (for debugging)
      - name: Show PYTHONPATH and Python sys.path
        run: |
          echo "PYTHONPATH: $PYTHONPATH"
          python -c "import sys; print(sys.path)"

      # Step 6: Run tests with PYTHONPATH
      - name: Run pytest with PYTHONPATH
        run: PYTHONPATH=src pytest tests/
